---
title: "Get up to speed"
format: html
engine: knitr
---

```{css}
#| echo: false
p {
  text-align: justify
}
```

This workshop has been concived as an Advanced workshop to provide a guide to develop new DataSHIELD packages. Nevertheless, it may happend that not so experienced users/developers enroll on the workshop or happen to find this online material without prior experience. It is for that matter that this section is included, to provide a basis of knowledge about DataSHIELD before embarking on this short but steep journey.

Here, we provide different reading materials that will be useful to create a solid basis about DataSHIELD.

+ [DataSHIELD paper](https://academic.oup.com/ije/article/43/6/1929/707730?login=true): Description of what is DataSHIELD.
+ [DataSHIELD wiki](https://data2knowledge.atlassian.net/wiki/spaces/DSDEV/overview): Materials about DataSHIELD including:
    + Beginner material
    + Recorded DataSHIELD workshops
    + Information on current release of DataSHIELD
+ [resource book](https://isglobal-brge.github.io/resource_bookdown/): In this book you will find information about:
    + DataSHIELD (Section 5)

Also, a shameless plug ^[From Xavier Escribà], if any reader finds this material is not enough, I encourage reading this [PhD thesis](https://www.tdx.cat/handle/10803/691737#page=1), where DataSHIELD is the center piece and it is explained in fine grained detail.

## Developing your first R package

During the workshop it will be assumed that the attendats have already prior knowledge about building a regular R package. If that was not the case, we provide some useful links to prepare in advance, as with the environment setup, feel free to contact the authors before the workshop to solve any doubts.

- [R packages](https://r-pkgs.org/)
- [usethis package](https://usethis.r-lib.org/index.html)
- [roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html)

::: {.callout-tip}
If you are not confident in your basic R package building skills, we suggest creating your first package before the workshop.

A good exercise would be to use the `usethis` package to setup the basic R package structure, create a simple `helloWorld()` function and document it using `roxygen2`.

[Here](https://github.com/ESCRI11/datashield-workshop-2024-exercises/tree/main/Exercise-0/testPackage), you can see how that would looke like once finished.
:::
